apiVersion: v1
kind: Service
metadata:
  name: todo
spec:
  selector:
    app: todo
  ports:
    - name: http
      port: 80
    - name: grpc
      port: 50051
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo
  labels:
    app: todo
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: todo
          image: andreymgn/rust-todo-todo:latest
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: 80
          env:
            - name: TODO_LOG_LEVEL
              value: "debug"
            - name: TODO_PORT
              value: "50051"
            - name: TODO_STORAGE
              value: "HashMap"
